server:
  port: 9123

logging:
  config: classpath:log4j2.xml

mail:
  recipient:
    #address: xuequnmou@aspirecn.com,caiyayu@aspirecn.com,hucy@aspirecn.com,chenggr@aspirecn.com,quanbopeng@aspirecn.com,caoweizhong@aspirecn.com,huangkai@aspirecn.com
    address: xuequnmou@aspirecn.com